# Generated by Django 3.2.2 on 2021-07-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('Bus_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bus_name', models.CharField(max_length=30)),
                ('Source', models.CharField(max_length=30)),
                ('Destination', models.CharField(max_length=30)),
                ('No_Seats', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('rate', models.IntegerField()),
                ('Deap_time', models.TimeField()),
                ('Reach_time', models.TimeField()),
                ('date', models.DateField()),
                ('BO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BOID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('Reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('SeatsReser', models.IntegerField()),
                ('Bus_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bus_Id', to='Busapp.bus')),
                ('Cus_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cus_Id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('cus', 'Customer'), ('bu', 'BusOwner'), ('abu', 'AdminBus')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_no', models.IntegerField()),
                ('Regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Busapp.reservation')),
            ],
        ),
    ]
