# Generated by Django 3.2.2 on 2021-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Busapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Av_Se',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
